import { useState } from "react";
import { json, redirect, type LoaderFunction, type ActionFunction } from "@remix-run/node";
import { useLoaderData, useFetcher } from "@remix-run/react";
import { createPost, getAllCategories, getAllTags, getAllTypes, getAuthorByAuthorId } from "../Services/post.server";
import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";
import { Label } from "../components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../components/ui/select";
import { Textarea } from "../components/ui/textarea";
import { useDropzone } from "react-dropzone";
import ReactMarkdown from "react-markdown";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { Category, Tag, Type } from "../Types/types";
import { Author } from "../models";
import { Types } from "mongoose";

// -------------------- Loader --------------------
export const loader: LoaderFunction = async () => {
  try {
    const [categories, tags, types] = await Promise.all([
      getAllCategories(),
      getAllTags(),
      getAllTypes(),
    ]);

    return json({ categories, tags, types });
  } catch (error) {
    return json({ categories: [], tags: [], types: [], error: "Failed to load data" }, { status: 500 });
  }
};

// -------------------- Action --------------------
export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();
  const title = formData.get("title")?.toString().trim() || "Untitled Post";
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const content = formData.get("content")?.toString() || "";
  const summary = formData.get("summary")?.toString() || "";
  // const seoTitle = formData.get("seoTitle")?.toString() || title;
  // const seoDescription = formData.get("seoDescription")?.toString() || summary;

  const author = await getAuthorByAuthorId("auth-001");
  if (!author) throw new Error("Author not found");

  const categories = formData.getAll("categories").filter(Boolean).map(id => ({ _id: String(id) }));
  const tags = formData.getAll("tags").filter(Boolean).map(String);
  const types = formData.getAll("types").filter(Boolean).map(String);

  const coverImage = formData.get("coverImage") as File | null;
  const gallery = formData.getAll("gallery").filter((f): f is File => f instanceof File);

  // const seo = {
  //   title: seoTitle,
  //   description: seoDescription,
  //   keywords: [],
  //   canonicalUrl: "",
  //   createdAt: new Date().toISOString(),
  //   updatedAt: new Date().toISOString(),
  // };

  await createPost(
    {
      title,
      slug,
      summary,
      content,
      categories,
      tags,
      types,
      date: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
      authorId: author._id.toString(), // add this
      author: new Types.ObjectId(author._id),
    },
    { coverImage, gallery }
  );


  return redirect("/admin/posts");
};

// -------------------- Component --------------------
export default function AdminPostCreate() {
  const { categories, tags, types, error } = useLoaderData<{
    categories: Category[];
    tags: Tag[];
    types: Type;
    error?: string;
  }>();
  const fetcher = useFetcher();
  const [contentMd, setContentMd] = useState("");
  const [coverFile, setCoverFile] = useState<File | null>(null);
  const [galleryFiles, setGalleryFiles] = useState<File[]>([]);

  const { getRootProps: getCoverProps, getInputProps: getCoverInput } = useDropzone({
    accept: { "image/*": [] },
    multiple: false,
    onDrop: (files) => setCoverFile(files[0]),
  });

  const { getRootProps: getGalleryProps, getInputProps: getGalleryInput } = useDropzone({
    accept: { "image/*": [] },
    multiple: true,
    onDrop: (files) => setGalleryFiles((prev) => [...prev, ...files]),
  });

  const { getRootProps: getMdProps, getInputProps: getMdInput } = useDropzone({
    accept: { "text/markdown": [".md"] },
    multiple: false,
    onDrop: async (files) => {
      const text = await files[0].text();
      setContentMd(text);
    },
  });

  const handleAutoFill = () => {
    const randomText = () => Math.random().toString(36).substring(2, 10);
    setContentMd(`# Sample Markdown\n\nAutogenerated content: ${randomText()}`);
    const titleInput = document.querySelector<HTMLInputElement>('input[name="title"]');
    const summaryInput = document.querySelector<HTMLTextAreaElement>('textarea[name="summary"]');
    if (titleInput) titleInput.value = `Title ${randomText()}`;
    // const seoTitleInput = document.querySelector<HTMLInputElement>('input[name="seoTitle"]');
    // const seoDescInput = document.querySelector<HTMLTextAreaElement>('textarea[name="seoDescription"]');
    // if (seoTitleInput) seoTitleInput.value = `SEO Title ${randomText()}`;
    // if (seoDescInput) seoDescInput.value = `SEO Desc ${randomText()}`;
    if (summaryInput) summaryInput.value = `Summary ${randomText()}`;
  };

  return (
    <div className="min-h-screen bg-zinc-900 m-4 text-zinc-100 font-sans">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <h1 className="text-2xl font-semibold text-zinc-100 mb-6">Create New Post</h1>
        {error && <div className="mb-4 p-4 bg-red-900/20 text-red-400 rounded-md">{error}</div>}
        <Button type="button" onClick={handleAutoFill} className="mb-4 bg-green-600 hover:bg-green-700 text-white">Auto-Fill</Button>

        <fetcher.Form method="post" encType="multipart/form-data" className="space-y-6">
          <InputField label="Title" name="title" required placeholder="Enter post title" />
          <TextareaField label="Summary" name="summary" placeholder="Brief summary of the post" />
          {/* <InputField label="SEO Title" name="seoTitle" placeholder="SEO-friendly title" />
          <TextareaField label="SEO Description" name="seoDescription" placeholder="SEO-friendly description" /> */}

          <Tabs defaultValue="write" className="space-y-4">
            <TabsList>
              <TabsTrigger value="write">Write Content</TabsTrigger>
              <TabsTrigger value="upload">Upload Markdown</TabsTrigger>
            </TabsList>
            <TabsContent value="write">
              <TextareaField label="Content (Markdown)" name="content" value={contentMd} onChange={e => setContentMd(e.target.value)} />
            </TabsContent>
            <TabsContent value="upload">
              <div {...getMdProps()} className="p-4 border border-dashed border-zinc-700 rounded-md cursor-pointer bg-zinc-800">
                <input {...getMdInput()} name="content" hidden />
                {contentMd ? <ReactMarkdown className="prose prose-invert max-w-none">{contentMd}</ReactMarkdown> : <p className="text-zinc-400">Drag & drop a .md file here or click</p>}
              </div>
            </TabsContent>
          </Tabs>

          <SelectField label="Categories" name="categories" options={categories.map(c => ({ value: c._id, label: c.name }))} multiple />
          <SelectField label="Tags" name="tags" options={tags.map(t => ({ value: t._id, label: t.name }))} multiple />
          <SelectField label="Types" name="types" options={types.map(t => ({ value: t._id, label: t.type }))} multiple />

          <FileDropzone label="Cover Image" getProps={getCoverProps} getInput={getCoverInput} files={coverFile ? [coverFile] : []} />
          <FileDropzone label="Gallery Images" getProps={getGalleryProps} getInput={getGalleryInput} files={galleryFiles} />

          <Button type="submit" className="bg-indigo-600 hover:bg-indigo-700 text-white" disabled={fetcher.state !== "idle"}>
            {fetcher.state === "submitting" ? "Creating..." : "Create Post"}
          </Button>
        </fetcher.Form>
      </div>
    </div>
  );
}

// -------------------- UI Helpers --------------------
function InputField({ label, ...props }: any) {
  return (
    <div>
      <Label className="text-zinc-300">{label}</Label>
      <Input className="bg-zinc-800 border-zinc-700 text-zinc-100 focus:ring-indigo-500" {...props} />
    </div>
  );
}
function TextareaField({ label, ...props }: any) {
  return (
    <div>
      <Label className="text-zinc-300">{label}</Label>
      <Textarea className="bg-zinc-800 border-zinc-700 text-zinc-100 focus:ring-indigo-500" {...props} />
    </div>
  );
}
function SelectField({ label, options, ...props }: any) {
  return (
    <div>
      <Label className="text-zinc-300">{label}</Label>
      <Select {...props} multiple>
        <SelectTrigger className="bg-zinc-800 border-zinc-700 text-zinc-100">
          <SelectValue placeholder={`Select ${label.toLowerCase()}`} />
        </SelectTrigger>
        <SelectContent className="bg-zinc-800 text-zinc-100 border-zinc-700">
          {options.map((opt: any) => <SelectItem key={opt.value} value={opt.value} className="hover:bg-zinc-700">{opt.label}</SelectItem>)}
        </SelectContent>
      </Select>
    </div>
  );
}
function FileDropzone({ label, getProps, getInput, files }: any) {
  return (
    <div>
      <Label className="text-zinc-300">{label}</Label>
      <div {...getProps()} className="p-4 border border-dashed border-zinc-700 rounded-md cursor-pointer dark:bg-zinc-900 bg-zinc-50 text-center">
        <input {...getInput()} />
        {files.length > 0 ? files.map((f: File) => <p key={f.name} className="text-zinc-400">{f.name}</p>) : <p className="text-zinc-400">Drag & drop or click to select</p>}
      </div>
    </div>
  );
}
